endpoints:
    - api-interface: tendermintrpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2221"
        # by default the connection will use a self signed certificate, which is not recommended 
        # (https connections wont be able to connect)

        # example with provider setting up a secure connection with a CA certificate
        key-pem: "/path/to/key.pem"
        cert-pem: "/path/to/cert.pem"
        # also you can specify disable-tls if you want to disable provider TLS settings in case 
        # you want to use a proxy server which has tls enabled.
        disable-tls: true
      node-urls:
        - url: ws://127.0.0.1:26657/websocket
          auth-config:
            auth-query: auth=xyz
            auth-headers:
              AUTH-X-HEADER: xyz
        - url: http://127.0.0.1:26657
          auth-config:
            auth-query: auth=xxyyzz
            auth-headers:
              AUTH-X-HEADER-2: xxyyzz
    - api-interface: grpc
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2221"
      node-urls: 
        - url: 127.0.0.1:9090
          auth-config:
            use-tls: true
            # selected key and cert
            key-pem: /home/user/key.pem
            cert-pem: /home/user/cert.pem
    - api-interface: grpc
      chain-id: OSMOSIS
      network-address:
        address: "127.0.0.1:2221"
      node-urls: 
        - url: 127.0.0.1:9093
          auth-config:
            # default tls cert
            use-tls: true 
    - api-interface: grpc
      chain-id: COSMOSHUB
      network-address:
        address: "127.0.0.1:2221"
      node-urls: 
        - url: 127.0.0.1:9096
          auth-config:
            use-tls: true 
            # root trusted certificate
            cacert-pem: /home/user/cert.pem 
    - api-interface: rest
      chain-id: LAV1
      network-address:
        address: "127.0.0.1:2221"
      node-urls: 
        - url: http://127.0.0.1:1317
          auth-config:
            auth-query: auth=banana
            auth-headers:
              AUTH-X-HEADER-2: xxyyzz
          timeout: 1s
          ip-forwarding: true
    - api-interface: jsonrpc
      chain-id: ETH1
      network-address:
        address: "127.0.0.1:2221"
      node-urls: 
        - url: ws://your_node_url/
          auth-config:
            auth-query: auth=banana
            auth-headers:
              AUTH-X-HEADER-2: xxyyzz
          ip-forwarding: true
          timeout: 10000000
metrics-listen-address: ":7780"