endpoints:
    - chain-id: LAV1
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3341
    - chain-id: LAV1
      api-interface: rest
      network-address: 127.0.0.1:3340
    - chain-id: LAV1
      api-interface: grpc
      network-address: 127.0.0.1:3352
    - chain-id: OSMOSIS
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3335
    - chain-id: OSMOSIS
      api-interface: rest
      network-address: 127.0.0.1:3334
    - chain-id: ETH1
      api-interface: jsonrpc
      network-address: 127.0.0.1:3333